dist: xenial
language: python
env:
  - IS_TRAVIS: true
os: linux
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "nightly"
install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Create the test environment and install the dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pip numpy>=1.14 scipy nomkl pyqt
  - source activate test-environment
  - pip install -r requirements-travis.txt
  - conda list
script: py.test --mypy --cov=xanespy tests/
after_success:
  - coveralls
